import '../styles/globals.css'
import { Font } from 'next/font/google'
import { Navigation } from '../components/Navigation'

// const font = Space_Grotesk({
//   weight: ['400', '700']
// })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>🙀</title>
        <Font family="Space Grotesk" weights={[400, 700]} />
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
