import '../styles/globals.css'
import { Navigation } from '../components/Navigation'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <title>My first app with Next JS 13</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
